//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaEF.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPizza
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<bool> IsVeg { get; set; }
        public Nullable<double> price { get; set; }
    }
}
